version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase-logging
    restart: unless-stopped
    environment:
      PB_HOST: http://localhost:8090
      PB_HOST_BK: https://logger.pockethost.io
    ports:
      - "8090:8090"
    volumes:
      - ./pb_public:/pb_public
      - ./pb_hooks:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5